### ISSUE TITLE
missing reference Aspose.Imaging

### ISSUE THREAD

**Issue by mhussein79** [asposeimaging/Aspose_Imaging_NET#1]
Hi,
I tried to download .net examples, whenever I try to build and run the solution I got error missing reference Aspose.Imaging which I couldnt find in the bin to add. 

Im using vs.net 2010 cs

Regards.
M.H.

**Comment by saqib-razzaq-aspose** [comment]
Hi Hussein,

Please download the library from http://www.aspose.com/community/files/51/.net-components/aspose.imaging-for-.net/default.aspx and install it and then add reference in the project.

You can find detail instructions at http://www.aspose.com/docs/display/imagingnet/Install+Aspose.Imaging+for+.NET.
